[2024-06-23T00:14:20.300+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-23T00:14:20.325+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pokemon_example.metricspokemonweights manual__2024-06-23T00:05:08.961109+00:00 [queued]>
[2024-06-23T00:14:20.335+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pokemon_example.metricspokemonweights manual__2024-06-23T00:05:08.961109+00:00 [queued]>
[2024-06-23T00:14:20.336+0000] {taskinstance.py:2306} INFO - Starting attempt 6 of 6
[2024-06-23T00:14:20.349+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): metricspokemonweights> on 2024-06-23 00:05:08.961109+00:00
[2024-06-23T00:14:20.355+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5927) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-23T00:14:20.357+0000] {standard_task_runner.py:63} INFO - Started process 5928 to run task
[2024-06-23T00:14:20.358+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pokemon_example', 'metricspokemonweights', 'manual__2024-06-23T00:05:08.961109+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/python_operators.py', '--cfg-path', '/tmp/tmp9l59svz7']
[2024-06-23T00:14:20.359+0000] {standard_task_runner.py:91} INFO - Job 82: Subtask metricspokemonweights
[2024-06-23T00:14:20.401+0000] {task_command.py:426} INFO - Running <TaskInstance: pokemon_example.metricspokemonweights manual__2024-06-23T00:05:08.961109+00:00 [running]> on host c357804a93ab
[2024-06-23T00:14:20.496+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pokemon_example' AIRFLOW_CTX_TASK_ID='metricspokemonweights' AIRFLOW_CTX_EXECUTION_DATE='2024-06-23T00:05:08.961109+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-23T00:05:08.961109+00:00'
[2024-06-23T00:14:20.496+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-23T00:14:20.498+0000] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvfwjk_us9 --system-site-packages --python=python
[2024-06-23T00:14:20.499+0000] {process_utils.py:187} INFO - Output:
[2024-06-23T00:14:21.247+0000] {process_utils.py:191} INFO - created virtual environment CPython3.12.3.final.0-64 in 243ms
[2024-06-23T00:14:21.248+0000] {process_utils.py:191} INFO -   creator CPython3Posix(dest=/tmp/venvfwjk_us9, clear=False, no_vcs_ignore=False, global=True)
[2024-06-23T00:14:21.248+0000] {process_utils.py:191} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-06-23T00:14:21.249+0000] {process_utils.py:191} INFO -     added seed packages: pip==24.0
[2024-06-23T00:14:21.249+0000] {process_utils.py:191} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-06-23T00:14:21.269+0000] {process_utils.py:183} INFO - Executing cmd: /tmp/venvfwjk_us9/bin/pip install -r /tmp/venvfwjk_us9/requirements.txt
[2024-06-23T00:14:21.270+0000] {process_utils.py:187} INFO - Output:
[2024-06-23T00:14:26.415+0000] {process_utils.py:191} INFO - 
[2024-06-23T00:14:26.416+0000] {process_utils.py:191} INFO - [notice] A new release of pip is available: 24.0 -> 24.1
[2024-06-23T00:14:26.417+0000] {process_utils.py:191} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-06-23T00:14:26.514+0000] {process_utils.py:183} INFO - Executing cmd: /tmp/venvfwjk_us9/bin/python /tmp/venv-call8fdx791h/script.py /tmp/venv-call8fdx791h/script.in /tmp/venv-call8fdx791h/script.out /tmp/venv-call8fdx791h/string_args.txt /tmp/venv-call8fdx791h/termination.log
[2024-06-23T00:14:26.515+0000] {process_utils.py:187} INFO - Output:
[2024-06-23T00:14:28.592+0000] {process_utils.py:191} INFO - ----------------------------------------------------------------------------------------------------
[2024-06-23T00:14:28.593+0000] {process_utils.py:191} INFO - raw data:
[2024-06-23T00:14:28.597+0000] {process_utils.py:191} INFO - [{'name': 'bulbasaur', 'url': 'https://pokeapi.co/api/v2/pokemon/1/', 'weight': 69, 'parent_cluster': 0, 'parent_centroid': 88.50000000000006}, {'name': 'ivysaur', 'url': 'https://pokeapi.co/api/v2/pokemon/2/', 'weight': 130, 'parent_cluster': 0, 'parent_centroid': 88.50000000000006}, {'name': 'venusaur', 'url': 'https://pokeapi.co/api/v2/pokemon/3/', 'weight': 1000, 'parent_cluster': 1, 'parent_centroid': 919.9999999999999}, {'name': 'charmander', 'url': 'https://pokeapi.co/api/v2/pokemon/4/', 'weight': 85, 'parent_cluster': 0, 'parent_centroid': 88.50000000000006}, {'name': 'charmeleon', 'url': 'https://pokeapi.co/api/v2/pokemon/5/', 'weight': 190, 'parent_cluster': 0, 'parent_centroid': 88.50000000000006}, {'name': 'charizard', 'url': 'https://pokeapi.co/api/v2/pokemon/6/', 'weight': 905, 'parent_cluster': 1, 'parent_centroid': 919.9999999999999}, {'name': 'squirtle', 'url': 'https://pokeapi.co/api/v2/pokemon/7/', 'weight': 90, 'parent_cluster': 0, 'parent_centroid': 88.50000000000006}, {'name': 'wartortle', 'url': 'https://pokeapi.co/api/v2/pokemon/8/', 'weight': 225, 'parent_cluster': 2, 'parent_centroid': 307.0}, {'name': 'blastoise', 'url': 'https://pokeapi.co/api/v2/pokemon/9/', 'weight': 855, 'parent_cluster': 1, 'parent_centroid': 919.9999999999999}, {'name': 'caterpie', 'url': 'https://pokeapi.co/api/v2/pokemon/10/', 'weight': 29, 'parent_cluster': 0, 'parent_centroid': 88.50000000000006}, {'name': 'metapod', 'url': 'https://pokeapi.co/api/v2/pokemon/11/', 'weight': 99, 'parent_cluster': 0, 'parent_centroid': 88.50000000000006}, {'name': 'butterfree', 'url': 'https://pokeapi.co/api/v2/pokemon/12/', 'weight': 320, 'parent_cluster': 2, 'parent_centroid': 307.0}, {'name': 'weedle', 'url': 'https://pokeapi.co/api/v2/pokemon/13/', 'weight': 32, 'parent_cluster': 0, 'parent_centroid': 88.50000000000006}, {'name': 'kakuna', 'url': 'https://pokeapi.co/api/v2/pokemon/14/', 'weight': 100, 'parent_cluster': 0, 'parent_centroid': 88.50000000000006}, {'name': 'beedrill', 'url': 'https://pokeapi.co/api/v2/pokemon/15/', 'weight': 295, 'parent_cluster': 2, 'parent_centroid': 307.0}, {'name': 'pidgey', 'url': 'https://pokeapi.co/api/v2/pokemon/16/', 'weight': 18, 'parent_cluster': 0, 'parent_centroid': 88.50000000000006}, {'name': 'pidgeotto', 'url': 'https://pokeapi.co/api/v2/pokemon/17/', 'weight': 300, 'parent_cluster': 2, 'parent_centroid': 307.0}, {'name': 'pidgeot', 'url': 'https://pokeapi.co/api/v2/pokemon/18/', 'weight': 395, 'parent_cluster': 2, 'parent_centroid': 307.0}, {'name': 'rattata', 'url': 'https://pokeapi.co/api/v2/pokemon/19/', 'weight': 35, 'parent_cluster': 0, 'parent_centroid': 88.50000000000006}, {'name': 'raticate', 'url': 'https://pokeapi.co/api/v2/pokemon/20/', 'weight': 185, 'parent_cluster': 0, 'parent_centroid': 88.50000000000006}]
[2024-06-23T00:14:28.597+0000] {process_utils.py:191} INFO - Traceback (most recent call last):
[2024-06-23T00:14:28.597+0000] {process_utils.py:191} INFO -   File "/tmp/venv-call8fdx791h/script.py", line 81, in <module>
[2024-06-23T00:14:28.598+0000] {process_utils.py:191} INFO -     res = metricspokemonweights(*arg_dict["args"], **arg_dict["kwargs"])
[2024-06-23T00:14:28.598+0000] {process_utils.py:191} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-23T00:14:28.598+0000] {process_utils.py:191} INFO -   File "/tmp/venv-call8fdx791h/script.py", line 27, in metricspokemonweights
[2024-06-23T00:14:28.598+0000] {process_utils.py:191} INFO -     print(i,':',json.dumps(j, indent=4))
[2024-06-23T00:14:28.599+0000] {process_utils.py:191} INFO -                 ^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-23T00:14:28.599+0000] {process_utils.py:191} INFO -   File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
[2024-06-23T00:14:28.599+0000] {process_utils.py:191} INFO -     **kw).encode(obj)
[2024-06-23T00:14:28.600+0000] {process_utils.py:191} INFO -           ^^^^^^^^^^^
[2024-06-23T00:14:28.600+0000] {process_utils.py:191} INFO -   File "/usr/local/lib/python3.12/json/encoder.py", line 202, in encode
[2024-06-23T00:14:28.600+0000] {process_utils.py:191} INFO -     chunks = list(chunks)
[2024-06-23T00:14:28.600+0000] {process_utils.py:191} INFO -              ^^^^^^^^^^^^
[2024-06-23T00:14:28.601+0000] {process_utils.py:191} INFO -   File "/usr/local/lib/python3.12/json/encoder.py", line 432, in _iterencode
[2024-06-23T00:14:28.601+0000] {process_utils.py:191} INFO -     yield from _iterencode_dict(o, _current_indent_level)
[2024-06-23T00:14:28.601+0000] {process_utils.py:191} INFO -   File "/usr/local/lib/python3.12/json/encoder.py", line 406, in _iterencode_dict
[2024-06-23T00:14:28.602+0000] {process_utils.py:191} INFO -     yield from chunks
[2024-06-23T00:14:28.602+0000] {process_utils.py:191} INFO -   File "/usr/local/lib/python3.12/json/encoder.py", line 439, in _iterencode
[2024-06-23T00:14:28.602+0000] {process_utils.py:191} INFO -     o = _default(o)
[2024-06-23T00:14:28.603+0000] {process_utils.py:191} INFO -         ^^^^^^^^^^^
[2024-06-23T00:14:28.603+0000] {process_utils.py:191} INFO -   File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
[2024-06-23T00:14:28.604+0000] {process_utils.py:191} INFO -     raise TypeError(f'Object of type {o.__class__.__name__} '
[2024-06-23T00:14:28.604+0000] {process_utils.py:191} INFO - TypeError: Object of type int32 is not JSON serializable
[2024-06-23T00:14:28.851+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-23T00:14:28.861+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 437, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 759, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 514, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
Object of type int32 is not JSON serializable
[2024-06-23T00:14:28.867+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pokemon_example, task_id=metricspokemonweights, run_id=manual__2024-06-23T00:05:08.961109+00:00, execution_date=20240623T000508, start_date=20240623T001420, end_date=20240623T001428
[2024-06-23T00:14:28.884+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 82 for task metricspokemonweights (Process returned non-zero exit status 1.
Object of type int32 is not JSON serializable; 5928)
[2024-06-23T00:14:28.906+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-23T00:14:28.921+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-23T00:14:28.924+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
